<?php

/**
 * Generates public/themes/nigeria/css/branding.css
 * from the original style.css: every rule that uses the template's
 * accent colors (#FFC206 / #FEC100) is copied verbatim, but with
 * CSS variables substituted, so brand colors can be changed from
 * the admin dashboard without touching the original stylesheet.
 *
 * Run: php scripts/generate_branding_css.php
 */
$css = file_get_contents(__DIR__ . '/../public/themes/nigeria/css/style.css');
if ($css === false) {
    fwrite(STDERR, "style.css not found\n");
    exit(1);
}

$replacements = [
    '#FFC206' => 'var(--brand-primary)',
    '#FEC100' => 'var(--brand-secondary)',
];

$out = "/* AUTO-GENERATED by scripts/generate_branding_css.php — do not edit by hand.\n"
    . "   Mirrors every accent-color rule from style.css using CSS variables,\n"
    . "   so brand colors are live-editable from the admin dashboard. */\n\n"
    . ":root {\n"
    . "    --brand-primary: #f71089;    /* Approved Logo Vibrant Magenta */\n"
    . "    --brand-secondary: #ff269e;  /* Lighter magenta/rose */\n"
    . "}\n\n";

$pos = 0;
$handled = [];
while (($p = strpos($css, '#FFC206', $pos)) !== false) {
    $ruleStart = strrpos(substr($css, 0, $p), '}');
    $ruleStart = $ruleStart === false ? 0 : $ruleStart + 1;
    $braceOpen = strpos($css, '{', $ruleStart);
    if ($braceOpen !== false && $braceOpen < $p) {
        $braceClose = strpos($css, '}', $p);
        $rule = substr($css, $ruleStart, $braceClose - $ruleStart + 1);
        $key = md5($rule);
        if (! isset($handled[$key])) {
            $handled[$key] = true;
            $out .= str_replace(array_keys($replacements), array_values($replacements), $rule) . "\n";
        }
    }
    $pos = $p + 7;
}

// Same pass for the secondary color
$pos = 0;
while (($p = strpos($css, '#FEC100', $pos)) !== false) {
    $ruleStart = strrpos(substr($css, 0, $p), '}');
    $ruleStart = $ruleStart === false ? 0 : $ruleStart + 1;
    $braceOpen = strpos($css, '{', $ruleStart);
    if ($braceOpen !== false && $braceOpen < $p) {
        $braceClose = strpos($css, '}', $p);
        $rule = substr($css, $ruleStart, $braceClose - $ruleStart + 1);
        $key = md5($rule);
        if (! isset($handled[$key])) {
            $handled[$key] = true;
            $out .= str_replace(array_keys($replacements), array_values($replacements), $rule) . "\n";
        }
    }
    $pos = $p + 7;
}

$target = __DIR__ . '/../public/themes/nigeria/css/branding.css';
file_put_contents($target, $out);
echo 'Wrote ' . $target . ' (' . count($handled) . " rules)\n";
